<?php

namespace App\Operational;

class OperationalActivationStates
{
    public const OPERATIONAL_READY = 'OPERATIONAL_READY';
    public const OPERATIONAL_ACTIVATING = 'OPERATIONAL_ACTIVATING';
    public const OPERATIONAL_ACTIVE = 'OPERATIONAL_ACTIVE';
    public const OPERATIONAL_FAILED = 'OPERATIONAL_FAILED';
    public const OPERATIONAL_ROLLBACK_PENDING = 'OPERATIONAL_ROLLBACK_PENDING';
    public const OPERATIONAL_ROLLING_BACK = 'OPERATIONAL_ROLLING_BACK';
    public const OPERATIONAL_ROLLBACK_FAILED = 'OPERATIONAL_ROLLBACK_FAILED';
    public const OPERATIONAL_ROLLED_BACK = 'OPERATIONAL_ROLLED_BACK';
    public const OPERATIONAL_RECONCILIATION_REQUIRED = 'OPERATIONAL_RECONCILIATION_REQUIRED';
}
