import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '../../lib/api';
import { toastError, toastSuccess } from '../../lib/toast';
import { Btn, Card, CardBody, CardHeader, FormGroup, PageHeader, Select, Spinner, Table, Td } from '../../components/UI';

export default function TeacherAllocationsPage() {
  const qc = useQueryClient();
  const [form, setForm] = useState({ teacher_id: '', subject_id: '', stream_id: '', academic_year_id: '', term_id: '' });
  const { data: meta = {} } = useQuery<any>({ queryKey: ['af-meta'], queryFn: () => api.get('/academic-foundation/meta').then(r => r.data) });
  const { data = [], isLoading } = useQuery<any[]>({ queryKey: ['teacher-subject-allocations'], queryFn: () => api.get('/academic-foundation/teacher-allocations').then(r => r.data) });
  const save = useMutation({ mutationFn: () => api.post('/academic-foundation/teacher-allocations', form), onSuccess: () => { qc.invalidateQueries({ queryKey: ['teacher-subject-allocations'] }); toastSuccess('Teacher allocated.'); }, onError: (e: any) => toastError(e.response?.data?.message ?? 'Could not allocate teacher.') });
  if (isLoading) return <Spinner />;
  return <div><PageHeader title="Teacher Subject Allocations" subtitle="Allocate teachers to subjects and streams for a year and term" /><Card style={{ marginBottom: 20 }}><CardHeader title="New Allocation" /><CardBody><div className="grid grid-cols-1 gap-3 md:grid-cols-5"><FormGroup label="Teacher"><Select value={form.teacher_id} onChange={e => setForm(f => ({ ...f, teacher_id: e.target.value }))}>{(meta.teachers ?? []).map((t: any) => <option key={t.id} value={t.id}>{t.name}</option>)}</Select></FormGroup><FormGroup label="Subject"><Select value={form.subject_id} onChange={e => setForm(f => ({ ...f, subject_id: e.target.value }))}>{(meta.subjects ?? []).map((s: any) => <option key={s.id} value={s.id}>{s.name}</option>)}</Select></FormGroup><FormGroup label="Stream"><Select value={form.stream_id} onChange={e => setForm(f => ({ ...f, stream_id: e.target.value }))}>{(meta.streams ?? []).map((s: any) => <option key={s.id} value={s.id}>{s.name}</option>)}</Select></FormGroup><FormGroup label="Year"><Select value={form.academic_year_id} onChange={e => setForm(f => ({ ...f, academic_year_id: e.target.value }))}>{(meta.academic_years ?? []).map((y: any) => <option key={y.id} value={y.id}>{y.name}</option>)}</Select></FormGroup><FormGroup label="Term"><Select value={form.term_id} onChange={e => setForm(f => ({ ...f, term_id: e.target.value }))}>{(meta.terms ?? []).map((t: any) => <option key={t.id} value={t.id}>{t.name}</option>)}</Select></FormGroup></div><Btn loading={save.isPending} onClick={() => save.mutate()}>Allocate Teacher</Btn></CardBody></Card><Card><CardHeader title="Allocations" /><Table headers={['Teacher', 'Subject', 'Stream', 'Year', 'Term']}>{data.map(a => <tr key={a.id}><Td>{a.teacher_name}<br /><span className="text-xs text-slate-500">{a.staff_id}</span></Td><Td>{a.subject_name}</Td><Td>{a.form_name} {a.stream_name}</Td><Td>{a.academic_year_name}</Td><Td>{a.term_name}</Td></tr>)}</Table></Card></div>;
}
