import React, { useState } from 'react';
import { useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '../../lib/api';
import { toastSuccess } from '../../lib/toast';
import { Badge, Btn, Card, CardBody, CardHeader, FormGroup, Input, PageHeader, Select, Spinner, Table, Td, Textarea } from '../../components/UI';

export default function BehaviourIncidentDetailsPage() {
  const { id } = useParams();
  const qc = useQueryClient();
  const [action, setAction] = useState({ action_type: 'verbal_warning', action_date: new Date().toISOString().slice(0, 10), description: '', parent_required: false, parent_notified: false, follow_up_date: '' });
  const { data: incident, isLoading } = useQuery({ queryKey: ['incident', id], queryFn: () => api.get(`/discipline/behaviour/incidents/${id}`).then(r => r.data), enabled: !!id });
  const status = useMutation({ mutationFn: (s: string) => api.post(`/discipline/behaviour/incidents/${id}/${s}`), onSuccess: () => { qc.invalidateQueries({ queryKey: ['incident', id] }); toastSuccess('Incident updated.'); } });
  const createAction = useMutation({ mutationFn: () => api.post('/discipline/actions', { ...action, behaviour_incident_id: Number(id), follow_up_date: action.follow_up_date || null }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['incident', id] }); toastSuccess('Action created.'); } });
  if (isLoading) return <Spinner />;
  return <div><PageHeader title={incident.incident_number} subtitle={`${incident.student_name} - ${incident.title}`} action={<div className="flex gap-2"><Btn variant="outline" onClick={() => status.mutate('review')}>Review</Btn><Btn variant="outline" onClick={() => status.mutate('escalate')}>Escalate</Btn><Btn variant="outline" onClick={() => status.mutate('close')}>Close</Btn></div>} /><div className="grid grid-cols-1 gap-5 xl:grid-cols-[1fr_420px]"><Card><CardHeader title="Incident Details" /><CardBody><div className="space-y-3 text-sm"><div><strong>Student:</strong> {incident.student_name}</div><div><strong>Category:</strong> {incident.category_name} <Badge variant={incident.category_type === 'positive' ? 'green' : 'red'}>{incident.category_type}</Badge></div><div><strong>Severity:</strong> {incident.severity}</div><div><strong>Status:</strong> {incident.review_status}</div><p className="rounded-lg bg-slate-50 p-3">{incident.description}</p></div></CardBody><CardHeader title="Action History" /><Table headers={['Action', 'Date', 'Status', 'Description']}>{(incident.actions ?? []).map((a: any) => <tr key={a.id}><Td>{a.action_number}<br /><span className="text-xs">{a.action_type.replaceAll('_', ' ')}</span></Td><Td>{a.action_date}</Td><Td>{a.status}</Td><Td>{a.description}</Td></tr>)}</Table></Card><Card><CardHeader title="Create Disciplinary Action" /><CardBody><FormGroup label="Action Type"><Select value={action.action_type} onChange={e => setAction(a => ({ ...a, action_type: e.target.value }))}><option value="verbal_warning">Verbal Warning</option><option value="written_warning">Written Warning</option><option value="parent_meeting">Parent Meeting</option><option value="detention">Detention</option><option value="suspension">Suspension</option><option value="headmaster_review">Headmaster Review</option><option value="counselling">Counselling</option><option value="other">Other</option></Select></FormGroup><FormGroup label="Action Date"><Input type="date" value={action.action_date} onChange={e => setAction(a => ({ ...a, action_date: e.target.value }))} /></FormGroup><FormGroup label="Follow Up Date"><Input type="date" value={action.follow_up_date} onChange={e => setAction(a => ({ ...a, follow_up_date: e.target.value }))} /></FormGroup><FormGroup label="Description"><Textarea value={action.description} onChange={e => setAction(a => ({ ...a, description: e.target.value }))} /></FormGroup><label className="mb-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={action.parent_required} onChange={e => setAction(a => ({ ...a, parent_required: e.target.checked }))} /> Parent required/notified</label><Btn loading={createAction.isPending} onClick={() => createAction.mutate()}>Create Action</Btn></CardBody></Card></div></div>;
}
