import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '../../lib/api';
import { toastError, toastSuccess } from '../../lib/toast';
import { Badge, Btn, Card, FormGroup, Input, Modal, PageHeader, Select, Spinner, Table, Td, Textarea } from '../../components/UI';

export default function BehaviourIncidentsPage() {
  const qc = useQueryClient();
  const [open, setOpen] = useState(false);
  const [studentSearch, setStudentSearch] = useState('');
  const [student, setStudent] = useState<any>(null);
  const [form, setForm] = useState({ academic_year_id: '', term_id: '', behaviour_category_id: '', incident_date: new Date().toISOString().slice(0, 10), title: '', description: '', severity: 'low' });
  const { data: incidents = [], isLoading } = useQuery<any[]>({ queryKey: ['behaviour-incidents'], queryFn: () => api.get('/discipline/behaviour/incidents').then(r => r.data) });
  const { data: meta = {} } = useQuery<any>({ queryKey: ['discipline-meta'], queryFn: () => api.get('/discipline/meta').then(r => r.data) });
  const cats = meta.behaviour_categories ?? [];
  const years = meta.academic_years ?? [];
  const terms = meta.terms ?? [];
  const { data: students = [] } = useQuery<any[]>({ queryKey: ['student-search', studentSearch], queryFn: () => api.get('/students', { params: { search: studentSearch } }).then(r => r.data.data), enabled: studentSearch.length >= 2 });
  const save = useMutation({ mutationFn: () => api.post('/discipline/behaviour/incidents', { ...form, student_id: student?.id }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['behaviour-incidents'] }); setOpen(false); toastSuccess('Incident recorded.'); }, onError: (e: any) => toastError(e.response?.data?.message ?? 'Could not record incident.') });
  if (isLoading) return <Spinner />;
  return <div><PageHeader title="Behaviour Incidents" subtitle="Record and track conduct, warnings, and disciplinary referrals" action={<Btn onClick={() => setOpen(true)}>Record Incident</Btn>} /><Card><Table headers={['Incident', 'Student', 'Category', 'Severity', 'Status', 'Date']}>{incidents.map(i => <tr key={i.id}><Td><Link className="font-semibold text-emerald-700" to={`/app/discipline/behaviour/incidents/${i.id}`}>{i.incident_number}</Link><br /><span className="text-xs">{i.title}</span></Td><Td>{i.student_name}<br /><span className="text-xs text-slate-500">{i.student_number}</span></Td><Td>{i.category_name}</Td><Td><Badge variant={i.severity === 'critical' || i.severity === 'high' ? 'red' : i.severity === 'medium' ? 'amber' : 'green'}>{i.severity}</Badge></Td><Td>{i.review_status}</Td><Td>{i.incident_date}</Td></tr>)}</Table></Card><Modal open={open} onClose={() => setOpen(false)} title="Record Incident"><FormGroup label="Student Search"><Input value={studentSearch} onChange={e => setStudentSearch(e.target.value)} placeholder="Search student" /></FormGroup>{student && <div className="mb-3 rounded-lg bg-emerald-50 p-3 text-sm font-semibold">{student.first_name} {student.last_name}</div>}<div className="mb-3 grid grid-cols-1 gap-2">{students.slice(0, 5).map(s => <button className="rounded border p-2 text-left" key={s.id} onClick={() => setStudent(s)}>{s.first_name} {s.last_name} <span className="text-xs text-slate-500">{s.student_number}</span></button>)}</div><div className="grid grid-cols-2 gap-3"><FormGroup label="Year"><Select value={form.academic_year_id} onChange={e => setForm(f => ({ ...f, academic_year_id: e.target.value }))}>{years.map(y => <option key={y.id} value={y.id}>{y.name}</option>)}</Select></FormGroup><FormGroup label="Term"><Select value={form.term_id} onChange={e => setForm(f => ({ ...f, term_id: e.target.value }))}>{terms.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</Select></FormGroup><FormGroup label="Category"><Select value={form.behaviour_category_id} onChange={e => setForm(f => ({ ...f, behaviour_category_id: e.target.value }))}>{cats.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Select></FormGroup><FormGroup label="Severity"><Select value={form.severity} onChange={e => setForm(f => ({ ...f, severity: e.target.value }))}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></Select></FormGroup></div><FormGroup label="Title"><Input value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))} /></FormGroup><FormGroup label="Description"><Textarea value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} /></FormGroup><div className="flex justify-end gap-2"><Btn variant="outline" onClick={() => setOpen(false)}>Cancel</Btn><Btn loading={save.isPending} onClick={() => save.mutate()}>Save</Btn></div></Modal></div>;
}
